# Generated by Django 5.2.17 on 2026-09-10 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MagazineDesign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "issue_label",
                    models.CharField(
                        help_text="Issue this layout belongs to, e.g. 'Issue #12'.",
                        max_length=100,
                    ),
                ),
                ("version", models.CharField(default="v1.0", max_length=20)),
                ("file", models.FileField(upload_to="designs/%Y/%m/")),
                ("notes_to_editor", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_REVIEW", "Pending Editor Review"),
                            ("APPROVED", "Approved"),
                            ("REVISION_REQUESTED", "Revision Requested"),
                            ("SUPERSEDED", "Superseded"),
                        ],
                        default="PENDING_REVIEW",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("revision_notes", models.TextField(blank=True)),
                (
                    "designer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="magazine_designs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="design_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("issue_label", "version"),
                        name="unique_design_version_per_issue",
                    )
                ],
            },
        ),
    ]
