# Generated by Django 5.2.17 on 2026-09-10 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("design", "0001_initial"),
        ("issues", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="magazinedesign",
            name="unique_design_version_per_issue",
        ),
        migrations.RemoveField(
            model_name="magazinedesign",
            name="issue_label",
        ),
        migrations.AddField(
            model_name="magazinedesign",
            name="issue",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="designs",
                to="issues.issue",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="magazinedesign",
            constraint=models.UniqueConstraint(
                fields=("issue", "version"), name="unique_design_version_per_issue"
            ),
        ),
    ]
