# Generated by Django 5.2.17 on 2026-09-10 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "design",
            "0002_remove_magazinedesign_unique_design_version_per_issue_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="magazinedesign",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="covers/%Y/%m/"),
        ),
    ]
