# Generated by Django 5.2.17 on 2026-09-17 03:28

import apps.common.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("design", "0003_magazinedesign_cover_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="magazinedesign",
            name="file_purged",
            field=models.BooleanField(
                default=False,
                help_text="The object has been removed from storage. The record is retained because the review history is metadata, not the file itself.",
            ),
        ),
        migrations.AddField(
            model_name="magazinedesign",
            name="file_size",
            field=models.PositiveBigIntegerField(
                default=0,
                help_text="Bytes, recorded at upload so storage can be reported without listing the bucket.",
            ),
        ),
        migrations.AddField(
            model_name="magazinedesign",
            name="purged_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="magazinedesign",
            name="file",
            field=models.FileField(
                storage=apps.common.storage.DeferredPrivateStorage(),
                upload_to="designs/%Y/%m/",
            ),
        ),
    ]
