# Generated by Django 5.2.17 on 2026-09-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editorial", "0002_alter_revisionnote_editor"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="returned_by_ai",
            field=models.BooleanField(default=False),
        ),
    ]
