# Generated by Django 5.2.17 on 2026-09-10 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editorial", "0003_article_returned_by_ai"),
        ("issues", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="issue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles",
                to="issues.issue",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="issue_order",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
