# Generated by Django 5.2.17 on 2026-09-10 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editorial", "0004_article_issue_article_issue_order"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="assigned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles_assigned",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="brief",
            field=models.TextField(
                blank=True,
                help_text="The topic, angle, and editorial direction given to the Writer.",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="deadline",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="status",
            field=models.CharField(
                choices=[
                    ("ASSIGNED", "Assigned"),
                    ("DRAFTING", "Drafting"),
                    ("AWAITING_EVALUATION", "Awaiting Evaluation"),
                    ("UNDER_REVIEW", "Under Review"),
                    ("REVISION_REQUESTED", "Revision Requested"),
                    ("APPROVED", "Approved"),
                    ("PUBLISHED", "Published"),
                    ("WITHDRAWN", "Withdrawn"),
                ],
                default="DRAFTING",
                max_length=25,
            ),
        ),
    ]
