# Generated by Django 5.2.17 on 2026-09-10 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editorial", "0006_article_excerpt_article_hero_caption_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="is_premium",
            field=models.BooleanField(default=False),
        ),
    ]
