# Generated by Django 5.2.17 on 2026-09-10 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editorial", "0008_articleversion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="status",
            field=models.CharField(
                choices=[
                    ("ASSIGNED", "Assigned"),
                    ("DRAFTING", "Drafting"),
                    ("AWAITING_EVALUATION", "Awaiting Evaluation"),
                    ("UNDER_REVIEW", "Under Review"),
                    ("REVISION_REQUESTED", "Revision Requested"),
                    ("PENDING_SIGNOFF", "Awaiting Publisher Sign-off"),
                    ("APPROVED", "Approved"),
                    ("PUBLISHED", "Published"),
                    ("WITHDRAWN", "Withdrawn"),
                ],
                default="DRAFTING",
                max_length=25,
            ),
        ),
    ]
