# Generated by Django 5.2.17 on 2026-09-12 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="minimum_articles",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="An issue below this count is not considered ready.",
            ),
        ),
    ]
