# Generated by Django 5.2.17 on 2026-10-06 09:01

from django.db import migrations
from django.utils import timezone


def backfill(apps, schema_editor):
    """Without this, every existing account would count as never changed,
    and the history would start empty. Each account's current password is
    dated today and recorded as its first history entry."""
    User = apps.get_model("accounts", "User")
    History = apps.get_model("accounts", "PasswordHistory")
    now = timezone.now()
    for u in User.objects.all():
        if u.password_changed_at is None:
            User.objects.filter(pk=u.pk).update(password_changed_at=now)
        if u.password and not u.password.startswith("!") and not History.objects.filter(user_id=u.pk).exists():
            History.objects.create(user_id=u.pk, password_hash=u.password)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_password_changed_at_passwordhistory"),
    ]

    operations = []
