# Generated by Django 5.2.17 on 2026-09-10 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "site_name",
                    models.CharField(default="BOSS Magazine PH", max_length=100),
                ),
                ("tagline", models.CharField(blank=True, max_length=200)),
                ("accent_colour", models.CharField(default="#1a2744", max_length=7)),
                ("articles_per_page", models.PositiveSmallIntegerField(default=12)),
                ("maintenance_mode", models.BooleanField(default=False)),
                (
                    "maintenance_message",
                    models.CharField(
                        default="BOSS Magazine is briefly unavailable while we make an update.",
                        max_length=255,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Platform settings",
                "verbose_name_plural": "Platform settings",
            },
        ),
    ]
